# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: BUILD-{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

# Skipping commits with particular message or from specific user
skip_commits:
  message: /\[ci-skip\]|\[skip-ci\]/      # Regex for matching commit message

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  matrix:
    - OS_ARCH: x86
      PY_VERSION: Python35
    - OS_ARCH: x64
      PY_VERSION: Python35-x64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - cmd: tools\appveyor-version.sh -s
  - cmd: call tools\gittag.cmd
  - set PATH=C:\%PY_VERSION%;C:\%PY_VERSION%\Scripts;C:\%PY_VERSION%\Lib;C:\%PY_VERSION%\DLLs;C:\%PY_VERSION%\Lib\lib-tk;%PATH%
  - pip install -r requirements.txt

# to run your custom scripts instead of automatic MSBuild
build_script:
  - tools\build-win.cmd
  
after_build:
  - 7z a %APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_VERSION%-win-%OS_ARCH%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: $(appveyor_project_name)-$(appveyor_build_version)-win-$(os_arch).zip
    name: arch 
    type: file

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

    # Deploy to GitHub Releases
  - provider: GitHub
    draft: false
    artifact: arch
    force_update: true
    auth_token:
      secure: xvdRGkzOEuKTSJLfHoaIAa0ZyzykruHlt9CRMG5lNB06sHV+Sukbh7z0u5GP8Jeq
    on:
      appveyor_repo_tag: true
  - provider: BinTray
    username: morpheby
    api_key:
        secure: lvUYiNDVXSjrdgZ17EMSG5o3bOwQ194HxOkiLrOAmYnTi+tuUcV3TYafwiSTQAPx
    subject: morpheby
    repo: $(APPVEYOR_PROJECT_NAME)
    package: $(APPVEYOR_PROJECT_NAME)
    version: $(VERSION_SHORT)
    publish: true
    override: true
    artifact: arch
    on:
      branch: master
